# Generated by Django 3.1.3 on 2020-11-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other')], default='Other', max_length=20)),
                ('name', models.CharField(max_length=200, null=True)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('reference_no', models.IntegerField(primary_key=True, serialize=False)),
                ('neutered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.animal')),
            ],
        ),
    ]
