# Generated by Django 3.1.3 on 2020-11-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201115_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
