# Generated by Django 3.1.3 on 2020-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_animal_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=20, null=True)),
                ('species_fostered', models.CharField(max_length=200, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
