# Generated by Django 3.1.3 on 2020-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=50, null=True)),
                ('summary', models.CharField(max_length=150, null=True)),
                ('para1', models.CharField(max_length=1500, null=True)),
                ('para2', models.CharField(max_length=1500, null=True)),
                ('para3', models.CharField(max_length=1500, null=True)),
                ('para4', models.CharField(max_length=1500, null=True)),
            ],
        ),
    ]
