# Generated by Django 3.1.3 on 2020-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='para1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='para2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='para3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='para4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
